# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-07 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juzgado',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='juzgado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
