# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-05 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcontrol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='audiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='caso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('e', models.CharField(max_length=20)),
                ('jd', models.IntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('expediente', models.CharField(max_length=100)),
                ('siniestro', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=200)),
                ('montoDemanda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incapacidadDemanda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('IBMDemanda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contrato', models.CharField(max_length=50)),
                ('fechaAccidente', models.DateField()),
                ('fechaAlta', models.DateField()),
                ('inscARTCM', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='juzgado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=10)),
                ('numeroDocumento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=250)),
            ],
        ),
    ]
